// Code generated by "enumer -text -type TokenType"; DO NOT EDIT.

package chroma

import (
	"fmt"
	"strings"
)

const _TokenTypeName = "IgnoreNoneOtherErrorCodeLineLineLinkLineTableTDLineTableLineRemovedLineAddedLineHighlightLineNumbersTableLineNumbersLinePreWrapperBackgroundEOFTypeKeywordKeywordConstantKeywordDeclarationKeywordNamespaceKeywordPseudoKeywordReservedKeywordTypeNameNameAttributeNameClassNameConstantNameDecoratorNameEntityNameExceptionNameKeywordNameLabelNameNamespaceNameOperatorNameOtherNamePseudoNamePropertyNameTagNameBuiltinNameBuiltinPseudoNameVariableNameVariableAnonymousNameVariableClassNameVariableGlobalNameVariableInstanceNameVariableMagicNameFunctionNameFunctionMagicLiteralLiteralDateLiteralOtherLiteralStringLiteralStringAffixLiteralStringAtomLiteralStringBacktickLiteralStringBooleanLiteralStringCharLiteralStringDelimiterLiteralStringDocLiteralStringDoubleLiteralStringEscapeLiteralStringHeredocLiteralStringInterpolLiteralStringNameLiteralStringOtherLiteralStringRegexLiteralStringSingleLiteralStringSymbolLiteralNumberLiteralNumberBinLiteralNumberFloatLiteralNumberHexLiteralNumberIntegerLiteralNumberIntegerLongLiteralNumberOctLiteralNumberByteOperatorOperatorWordPunctuationCommentCommentHashbangCommentMultilineCommentSingleCommentSpecialCommentPreprocCommentPreprocFileGenericGenericDeletedGenericEmphGenericErrorGenericHeadingGenericInsertedGenericOutputGenericPromptGenericStrongGenericSubheadingGenericTracebackGenericUnderlineTextTextWhitespaceTextSymbolTextPunctuation"
const _TokenTypeLowerName = "ignorenoneothererrorcodelinelinelinklinetabletdlinetablelineremovedlineaddedlinehighlightlinenumberstablelinenumberslineprewrapperbackgroundeoftypekeywordkeywordconstantkeyworddeclarationkeywordnamespacekeywordpseudokeywordreservedkeywordtypenamenameattributenameclassnameconstantnamedecoratornameentitynameexceptionnamekeywordnamelabelnamenamespacenameoperatornameothernamepseudonamepropertynametagnamebuiltinnamebuiltinpseudonamevariablenamevariableanonymousnamevariableclassnamevariableglobalnamevariableinstancenamevariablemagicnamefunctionnamefunctionmagicliteralliteraldateliteralotherliteralstringliteralstringaffixliteralstringatomliteralstringbacktickliteralstringbooleanliteralstringcharliteralstringdelimiterliteralstringdocliteralstringdoubleliteralstringescapeliteralstringheredocliteralstringinterpolliteralstringnameliteralstringotherliteralstringregexliteralstringsingleliteralstringsymbolliteralnumberliteralnumberbinliteralnumberfloatliteralnumberhexliteralnumberintegerliteralnumberintegerlongliteralnumberoctliteralnumberbyteoperatoroperatorwordpunctuationcommentcommenthashbangcommentmultilinecommentsinglecommentspecialcommentpreproccommentpreprocfilegenericgenericdeletedgenericemphgenericerrorgenericheadinggenericinsertedgenericoutputgenericpromptgenericstronggenericsubheadinggenerictracebackgenericunderlinetexttextwhitespacetextsymboltextpunctuation"

var _TokenTypeMap = map[TokenType]string{
	-16:  _TokenTypeName[0:6],
	-15:  _TokenTypeName[6:10],
	-14:  _TokenTypeName[10:15],
	-13:  _TokenTypeName[15:20],
	-12:  _TokenTypeName[20:28],
	-11:  _TokenTypeName[28:36],
	-10:  _TokenTypeName[36:47],
	-9:   _TokenTypeName[47:56],
	-8:   _TokenTypeName[56:67],
	-7:   _TokenTypeName[67:76],
	-6:   _TokenTypeName[76:89],
	-5:   _TokenTypeName[89:105],
	-4:   _TokenTypeName[105:116],
	-3:   _TokenTypeName[116:120],
	-2:   _TokenTypeName[120:130],
	-1:   _TokenTypeName[130:140],
	0:    _TokenTypeName[140:147],
	1000: _TokenTypeName[147:154],
	1001: _TokenTypeName[154:169],
	1002: _TokenTypeName[169:187],
	1003: _TokenTypeName[187:203],
	1004: _TokenTypeName[203:216],
	1005: _TokenTypeName[216:231],
	1006: _TokenTypeName[231:242],
	2000: _TokenTypeName[242:246],
	2001: _TokenTypeName[246:259],
	2002: _TokenTypeName[259:268],
	2003: _TokenTypeName[268:280],
	2004: _TokenTypeName[280:293],
	2005: _TokenTypeName[293:303],
	2006: _TokenTypeName[303:316],
	2007: _TokenTypeName[316:327],
	2008: _TokenTypeName[327:336],
	2009: _TokenTypeName[336:349],
	2010: _TokenTypeName[349:361],
	2011: _TokenTypeName[361:370],
	2012: _TokenTypeName[370:380],
	2013: _TokenTypeName[380:392],
	2014: _TokenTypeName[392:399],
	2100: _TokenTypeName[399:410],
	2101: _TokenTypeName[410:427],
	2200: _TokenTypeName[427:439],
	2201: _TokenTypeName[439:460],
	2202: _TokenTypeName[460:477],
	2203: _TokenTypeName[477:495],
	2204: _TokenTypeName[495:515],
	2205: _TokenTypeName[515:532],
	2300: _TokenTypeName[532:544],
	2301: _TokenTypeName[544:561],
	3000: _TokenTypeName[561:568],
	3001: _TokenTypeName[568:579],
	3002: _TokenTypeName[579:591],
	3100: _TokenTypeName[591:604],
	3101: _TokenTypeName[604:622],
	3102: _TokenTypeName[622:639],
	3103: _TokenTypeName[639:660],
	3104: _TokenTypeName[660:680],
	3105: _TokenTypeName[680:697],
	3106: _TokenTypeName[697:719],
	3107: _TokenTypeName[719:735],
	3108: _TokenTypeName[735:754],
	3109: _TokenTypeName[754:773],
	3110: _TokenTypeName[773:793],
	3111: _TokenTypeName[793:814],
	3112: _TokenTypeName[814:831],
	3113: _TokenTypeName[831:849],
	3114: _TokenTypeName[849:867],
	3115: _TokenTypeName[867:886],
	3116: _TokenTypeName[886:905],
	3200: _TokenTypeName[905:918],
	3201: _TokenTypeName[918:934],
	3202: _TokenTypeName[934:952],
	3203: _TokenTypeName[952:968],
	3204: _TokenTypeName[968:988],
	3205: _TokenTypeName[988:1012],
	3206: _TokenTypeName[1012:1028],
	3207: _TokenTypeName[1028:1045],
	4000: _TokenTypeName[1045:1053],
	4001: _TokenTypeName[1053:1065],
	5000: _TokenTypeName[1065:1076],
	6000: _TokenTypeName[1076:1083],
	6001: _TokenTypeName[1083:1098],
	6002: _TokenTypeName[1098:1114],
	6003: _TokenTypeName[1114:1127],
	6004: _TokenTypeName[1127:1141],
	6100: _TokenTypeName[1141:1155],
	6101: _TokenTypeName[1155:1173],
	7000: _TokenTypeName[1173:1180],
	7001: _TokenTypeName[1180:1194],
	7002: _TokenTypeName[1194:1205],
	7003: _TokenTypeName[1205:1217],
	7004: _TokenTypeName[1217:1231],
	7005: _TokenTypeName[1231:1246],
	7006: _TokenTypeName[1246:1259],
	7007: _TokenTypeName[1259:1272],
	7008: _TokenTypeName[1272:1285],
	7009: _TokenTypeName[1285:1302],
	7010: _TokenTypeName[1302:1318],
	7011: _TokenTypeName[1318:1334],
	8000: _TokenTypeName[1334:1338],
	8001: _TokenTypeName[1338:1352],
	8002: _TokenTypeName[1352:1362],
	8003: _TokenTypeName[1362:1377],
}

func (i TokenType) String() string {
	if str, ok := _TokenTypeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("TokenType(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TokenTypeNoOp() {
	var x [1]struct{}
	_ = x[Ignore-(-16)]
	_ = x[None-(-15)]
	_ = x[Other-(-14)]
	_ = x[Error-(-13)]
	_ = x[CodeLine-(-12)]
	_ = x[LineLink-(-11)]
	_ = x[LineTableTD-(-10)]
	_ = x[LineTable-(-9)]
	_ = x[LineRemoved-(-8)]
	_ = x[LineAdded-(-7)]
	_ = x[LineHighlight-(-6)]
	_ = x[LineNumbersTable-(-5)]
	_ = x[LineNumbers-(-4)]
	_ = x[Line-(-3)]
	_ = x[PreWrapper-(-2)]
	_ = x[Background-(-1)]
	_ = x[EOFType-(0)]
	_ = x[Keyword-(1000)]
	_ = x[KeywordConstant-(1001)]
	_ = x[KeywordDeclaration-(1002)]
	_ = x[KeywordNamespace-(1003)]
	_ = x[KeywordPseudo-(1004)]
	_ = x[KeywordReserved-(1005)]
	_ = x[KeywordType-(1006)]
	_ = x[Name-(2000)]
	_ = x[NameAttribute-(2001)]
	_ = x[NameClass-(2002)]
	_ = x[NameConstant-(2003)]
	_ = x[NameDecorator-(2004)]
	_ = x[NameEntity-(2005)]
	_ = x[NameException-(2006)]
	_ = x[NameKeyword-(2007)]
	_ = x[NameLabel-(2008)]
	_ = x[NameNamespace-(2009)]
	_ = x[NameOperator-(2010)]
	_ = x[NameOther-(2011)]
	_ = x[NamePseudo-(2012)]
	_ = x[NameProperty-(2013)]
	_ = x[NameTag-(2014)]
	_ = x[NameBuiltin-(2100)]
	_ = x[NameBuiltinPseudo-(2101)]
	_ = x[NameVariable-(2200)]
	_ = x[NameVariableAnonymous-(2201)]
	_ = x[NameVariableClass-(2202)]
	_ = x[NameVariableGlobal-(2203)]
	_ = x[NameVariableInstance-(2204)]
	_ = x[NameVariableMagic-(2205)]
	_ = x[NameFunction-(2300)]
	_ = x[NameFunctionMagic-(2301)]
	_ = x[Literal-(3000)]
	_ = x[LiteralDate-(3001)]
	_ = x[LiteralOther-(3002)]
	_ = x[LiteralString-(3100)]
	_ = x[LiteralStringAffix-(3101)]
	_ = x[LiteralStringAtom-(3102)]
	_ = x[LiteralStringBacktick-(3103)]
	_ = x[LiteralStringBoolean-(3104)]
	_ = x[LiteralStringChar-(3105)]
	_ = x[LiteralStringDelimiter-(3106)]
	_ = x[LiteralStringDoc-(3107)]
	_ = x[LiteralStringDouble-(3108)]
	_ = x[LiteralStringEscape-(3109)]
	_ = x[LiteralStringHeredoc-(3110)]
	_ = x[LiteralStringInterpol-(3111)]
	_ = x[LiteralStringName-(3112)]
	_ = x[LiteralStringOther-(3113)]
	_ = x[LiteralStringRegex-(3114)]
	_ = x[LiteralStringSingle-(3115)]
	_ = x[LiteralStringSymbol-(3116)]
	_ = x[LiteralNumber-(3200)]
	_ = x[LiteralNumberBin-(3201)]
	_ = x[LiteralNumberFloat-(3202)]
	_ = x[LiteralNumberHex-(3203)]
	_ = x[LiteralNumberInteger-(3204)]
	_ = x[LiteralNumberIntegerLong-(3205)]
	_ = x[LiteralNumberOct-(3206)]
	_ = x[LiteralNumberByte-(3207)]
	_ = x[Operator-(4000)]
	_ = x[OperatorWord-(4001)]
	_ = x[Punctuation-(5000)]
	_ = x[Comment-(6000)]
	_ = x[CommentHashbang-(6001)]
	_ = x[CommentMultiline-(6002)]
	_ = x[CommentSingle-(6003)]
	_ = x[CommentSpecial-(6004)]
	_ = x[CommentPreproc-(6100)]
	_ = x[CommentPreprocFile-(6101)]
	_ = x[Generic-(7000)]
	_ = x[GenericDeleted-(7001)]
	_ = x[GenericEmph-(7002)]
	_ = x[GenericError-(7003)]
	_ = x[GenericHeading-(7004)]
	_ = x[GenericInserted-(7005)]
	_ = x[GenericOutput-(7006)]
	_ = x[GenericPrompt-(7007)]
	_ = x[GenericStrong-(7008)]
	_ = x[GenericSubheading-(7009)]
	_ = x[GenericTraceback-(7010)]
	_ = x[GenericUnderline-(7011)]
	_ = x[Text-(8000)]
	_ = x[TextWhitespace-(8001)]
	_ = x[TextSymbol-(8002)]
	_ = x[TextPunctuation-(8003)]
}

var _TokenTypeValues = []TokenType{Ignore, None, Other, Error, CodeLine, LineLink, LineTableTD, LineTable, LineRemoved, LineAdded, LineHighlight, LineNumbersTable, LineNumbers, Line, PreWrapper, Background, EOFType, Keyword, KeywordConstant, KeywordDeclaration, KeywordNamespace, KeywordPseudo, KeywordReserved, KeywordType, Name, NameAttribute, NameClass, NameConstant, NameDecorator, NameEntity, NameException, NameKeyword, NameLabel, NameNamespace, NameOperator, NameOther, NamePseudo, NameProperty, NameTag, NameBuiltin, NameBuiltinPseudo, NameVariable, NameVariableAnonymous, NameVariableClass, NameVariableGlobal, NameVariableInstance, NameVariableMagic, NameFunction, NameFunctionMagic, Literal, LiteralDate, LiteralOther, LiteralString, LiteralStringAffix, LiteralStringAtom, LiteralStringBacktick, LiteralStringBoolean, LiteralStringChar, LiteralStringDelimiter, LiteralStringDoc, LiteralStringDouble, LiteralStringEscape, LiteralStringHeredoc, LiteralStringInterpol, LiteralStringName, LiteralStringOther, LiteralStringRegex, LiteralStringSingle, LiteralStringSymbol, LiteralNumber, LiteralNumberBin, LiteralNumberFloat, LiteralNumberHex, LiteralNumberInteger, LiteralNumberIntegerLong, LiteralNumberOct, LiteralNumberByte, Operator, OperatorWord, Punctuation, Comment, CommentHashbang, CommentMultiline, CommentSingle, CommentSpecial, CommentPreproc, CommentPreprocFile, Generic, GenericDeleted, GenericEmph, GenericError, GenericHeading, GenericInserted, GenericOutput, GenericPrompt, GenericStrong, GenericSubheading, GenericTraceback, GenericUnderline, Text, TextWhitespace, TextSymbol, TextPunctuation}

var _TokenTypeNameToValueMap = map[string]TokenType{
	_TokenTypeName[0:6]:            Ignore,
	_TokenTypeLowerName[0:6]:       Ignore,
	_TokenTypeName[6:10]:           None,
	_TokenTypeLowerName[6:10]:      None,
	_TokenTypeName[10:15]:          Other,
	_TokenTypeLowerName[10:15]:     Other,
	_TokenTypeName[15:20]:          Error,
	_TokenTypeLowerName[15:20]:     Error,
	_TokenTypeName[20:28]:          CodeLine,
	_TokenTypeLowerName[20:28]:     CodeLine,
	_TokenTypeName[28:36]:          LineLink,
	_TokenTypeLowerName[28:36]:     LineLink,
	_TokenTypeName[36:47]:          LineTableTD,
	_TokenTypeLowerName[36:47]:     LineTableTD,
	_TokenTypeName[47:56]:          LineTable,
	_TokenTypeLowerName[47:56]:     LineTable,
	_TokenTypeName[56:67]:          LineRemoved,
	_TokenTypeLowerName[56:67]:     LineRemoved,
	_TokenTypeName[67:76]:          LineAdded,
	_TokenTypeLowerName[67:76]:     LineAdded,
	_TokenTypeName[76:89]:          LineHighlight,
	_TokenTypeLowerName[76:89]:     LineHighlight,
	_TokenTypeName[89:105]:         LineNumbersTable,
	_TokenTypeLowerName[89:105]:    LineNumbersTable,
	_TokenTypeName[105:116]:        LineNumbers,
	_TokenTypeLowerName[105:116]:   LineNumbers,
	_TokenTypeName[116:120]:        Line,
	_TokenTypeLowerName[116:120]:   Line,
	_TokenTypeName[120:130]:        PreWrapper,
	_TokenTypeLowerName[120:130]:   PreWrapper,
	_TokenTypeName[130:140]:        Background,
	_TokenTypeLowerName[130:140]:   Background,
	_TokenTypeName[140:147]:        EOFType,
	_TokenTypeLowerName[140:147]:   EOFType,
	_TokenTypeName[147:154]:        Keyword,
	_TokenTypeLowerName[147:154]:   Keyword,
	_TokenTypeName[154:169]:        KeywordConstant,
	_TokenTypeLowerName[154:169]:   KeywordConstant,
	_TokenTypeName[169:187]:        KeywordDeclaration,
	_TokenTypeLowerName[169:187]:   KeywordDeclaration,
	_TokenTypeName[187:203]:        KeywordNamespace,
	_TokenTypeLowerName[187:203]:   KeywordNamespace,
	_TokenTypeName[203:216]:        KeywordPseudo,
	_TokenTypeLowerName[203:216]:   KeywordPseudo,
	_TokenTypeName[216:231]:        KeywordReserved,
	_TokenTypeLowerName[216:231]:   KeywordReserved,
	_TokenTypeName[231:242]:        KeywordType,
	_TokenTypeLowerName[231:242]:   KeywordType,
	_TokenTypeName[242:246]:        Name,
	_TokenTypeLowerName[242:246]:   Name,
	_TokenTypeName[246:259]:        NameAttribute,
	_TokenTypeLowerName[246:259]:   NameAttribute,
	_TokenTypeName[259:268]:        NameClass,
	_TokenTypeLowerName[259:268]:   NameClass,
	_TokenTypeName[268:280]:        NameConstant,
	_TokenTypeLowerName[268:280]:   NameConstant,
	_TokenTypeName[280:293]:        NameDecorator,
	_TokenTypeLowerName[280:293]:   NameDecorator,
	_TokenTypeName[293:303]:        NameEntity,
	_TokenTypeLowerName[293:303]:   NameEntity,
	_TokenTypeName[303:316]:        NameException,
	_TokenTypeLowerName[303:316]:   NameException,
	_TokenTypeName[316:327]:        NameKeyword,
	_TokenTypeLowerName[316:327]:   NameKeyword,
	_TokenTypeName[327:336]:        NameLabel,
	_TokenTypeLowerName[327:336]:   NameLabel,
	_TokenTypeName[336:349]:        NameNamespace,
	_TokenTypeLowerName[336:349]:   NameNamespace,
	_TokenTypeName[349:361]:        NameOperator,
	_TokenTypeLowerName[349:361]:   NameOperator,
	_TokenTypeName[361:370]:        NameOther,
	_TokenTypeLowerName[361:370]:   NameOther,
	_TokenTypeName[370:380]:        NamePseudo,
	_TokenTypeLowerName[370:380]:   NamePseudo,
	_TokenTypeName[380:392]:        NameProperty,
	_TokenTypeLowerName[380:392]:   NameProperty,
	_TokenTypeName[392:399]:        NameTag,
	_TokenTypeLowerName[392:399]:   NameTag,
	_TokenTypeName[399:410]:        NameBuiltin,
	_TokenTypeLowerName[399:410]:   NameBuiltin,
	_TokenTypeName[410:427]:        NameBuiltinPseudo,
	_TokenTypeLowerName[410:427]:   NameBuiltinPseudo,
	_TokenTypeName[427:439]:        NameVariable,
	_TokenTypeLowerName[427:439]:   NameVariable,
	_TokenTypeName[439:460]:        NameVariableAnonymous,
	_TokenTypeLowerName[439:460]:   NameVariableAnonymous,
	_TokenTypeName[460:477]:        NameVariableClass,
	_TokenTypeLowerName[460:477]:   NameVariableClass,
	_TokenTypeName[477:495]:        NameVariableGlobal,
	_TokenTypeLowerName[477:495]:   NameVariableGlobal,
	_TokenTypeName[495:515]:        NameVariableInstance,
	_TokenTypeLowerName[495:515]:   NameVariableInstance,
	_TokenTypeName[515:532]:        NameVariableMagic,
	_TokenTypeLowerName[515:532]:   NameVariableMagic,
	_TokenTypeName[532:544]:        NameFunction,
	_TokenTypeLowerName[532:544]:   NameFunction,
	_TokenTypeName[544:561]:        NameFunctionMagic,
	_TokenTypeLowerName[544:561]:   NameFunctionMagic,
	_TokenTypeName[561:568]:        Literal,
	_TokenTypeLowerName[561:568]:   Literal,
	_TokenTypeName[568:579]:        LiteralDate,
	_TokenTypeLowerName[568:579]:   LiteralDate,
	_TokenTypeName[579:591]:        LiteralOther,
	_TokenTypeLowerName[579:591]:   LiteralOther,
	_TokenTypeName[591:604]:        LiteralString,
	_TokenTypeLowerName[591:604]:   LiteralString,
	_TokenTypeName[604:622]:        LiteralStringAffix,
	_TokenTypeLowerName[604:622]:   LiteralStringAffix,
	_TokenTypeName[622:639]:        LiteralStringAtom,
	_TokenTypeLowerName[622:639]:   LiteralStringAtom,
	_TokenTypeName[639:660]:        LiteralStringBacktick,
	_TokenTypeLowerName[639:660]:   LiteralStringBacktick,
	_TokenTypeName[660:680]:        LiteralStringBoolean,
	_TokenTypeLowerName[660:680]:   LiteralStringBoolean,
	_TokenTypeName[680:697]:        LiteralStringChar,
	_TokenTypeLowerName[680:697]:   LiteralStringChar,
	_TokenTypeName[697:719]:        LiteralStringDelimiter,
	_TokenTypeLowerName[697:719]:   LiteralStringDelimiter,
	_TokenTypeName[719:735]:        LiteralStringDoc,
	_TokenTypeLowerName[719:735]:   LiteralStringDoc,
	_TokenTypeName[735:754]:        LiteralStringDouble,
	_TokenTypeLowerName[735:754]:   LiteralStringDouble,
	_TokenTypeName[754:773]:        LiteralStringEscape,
	_TokenTypeLowerName[754:773]:   LiteralStringEscape,
	_TokenTypeName[773:793]:        LiteralStringHeredoc,
	_TokenTypeLowerName[773:793]:   LiteralStringHeredoc,
	_TokenTypeName[793:814]:        LiteralStringInterpol,
	_TokenTypeLowerName[793:814]:   LiteralStringInterpol,
	_TokenTypeName[814:831]:        LiteralStringName,
	_TokenTypeLowerName[814:831]:   LiteralStringName,
	_TokenTypeName[831:849]:        LiteralStringOther,
	_TokenTypeLowerName[831:849]:   LiteralStringOther,
	_TokenTypeName[849:867]:        LiteralStringRegex,
	_TokenTypeLowerName[849:867]:   LiteralStringRegex,
	_TokenTypeName[867:886]:        LiteralStringSingle,
	_TokenTypeLowerName[867:886]:   LiteralStringSingle,
	_TokenTypeName[886:905]:        LiteralStringSymbol,
	_TokenTypeLowerName[886:905]:   LiteralStringSymbol,
	_TokenTypeName[905:918]:        LiteralNumber,
	_TokenTypeLowerName[905:918]:   LiteralNumber,
	_TokenTypeName[918:934]:        LiteralNumberBin,
	_TokenTypeLowerName[918:934]:   LiteralNumberBin,
	_TokenTypeName[934:952]:        LiteralNumberFloat,
	_TokenTypeLowerName[934:952]:   LiteralNumberFloat,
	_TokenTypeName[952:968]:        LiteralNumberHex,
	_TokenTypeLowerName[952:968]:   LiteralNumberHex,
	_TokenTypeName[968:988]:        LiteralNumberInteger,
	_TokenTypeLowerName[968:988]:   LiteralNumberInteger,
	_TokenTypeName[988:1012]:       LiteralNumberIntegerLong,
	_TokenTypeLowerName[988:1012]:  LiteralNumberIntegerLong,
	_TokenTypeName[1012:1028]:      LiteralNumberOct,
	_TokenTypeLowerName[1012:1028]: LiteralNumberOct,
	_TokenTypeName[1028:1045]:      LiteralNumberByte,
	_TokenTypeLowerName[1028:1045]: LiteralNumberByte,
	_TokenTypeName[1045:1053]:      Operator,
	_TokenTypeLowerName[1045:1053]: Operator,
	_TokenTypeName[1053:1065]:      OperatorWord,
	_TokenTypeLowerName[1053:1065]: OperatorWord,
	_TokenTypeName[1065:1076]:      Punctuation,
	_TokenTypeLowerName[1065:1076]: Punctuation,
	_TokenTypeName[1076:1083]:      Comment,
	_TokenTypeLowerName[1076:1083]: Comment,
	_TokenTypeName[1083:1098]:      CommentHashbang,
	_TokenTypeLowerName[1083:1098]: CommentHashbang,
	_TokenTypeName[1098:1114]:      CommentMultiline,
	_TokenTypeLowerName[1098:1114]: CommentMultiline,
	_TokenTypeName[1114:1127]:      CommentSingle,
	_TokenTypeLowerName[1114:1127]: CommentSingle,
	_TokenTypeName[1127:1141]:      CommentSpecial,
	_TokenTypeLowerName[1127:1141]: CommentSpecial,
	_TokenTypeName[1141:1155]:      CommentPreproc,
	_TokenTypeLowerName[1141:1155]: CommentPreproc,
	_TokenTypeName[1155:1173]:      CommentPreprocFile,
	_TokenTypeLowerName[1155:1173]: CommentPreprocFile,
	_TokenTypeName[1173:1180]:      Generic,
	_TokenTypeLowerName[1173:1180]: Generic,
	_TokenTypeName[1180:1194]:      GenericDeleted,
	_TokenTypeLowerName[1180:1194]: GenericDeleted,
	_TokenTypeName[1194:1205]:      GenericEmph,
	_TokenTypeLowerName[1194:1205]: GenericEmph,
	_TokenTypeName[1205:1217]:      GenericError,
	_TokenTypeLowerName[1205:1217]: GenericError,
	_TokenTypeName[1217:1231]:      GenericHeading,
	_TokenTypeLowerName[1217:1231]: GenericHeading,
	_TokenTypeName[1231:1246]:      GenericInserted,
	_TokenTypeLowerName[1231:1246]: GenericInserted,
	_TokenTypeName[1246:1259]:      GenericOutput,
	_TokenTypeLowerName[1246:1259]: GenericOutput,
	_TokenTypeName[1259:1272]:      GenericPrompt,
	_TokenTypeLowerName[1259:1272]: GenericPrompt,
	_TokenTypeName[1272:1285]:      GenericStrong,
	_TokenTypeLowerName[1272:1285]: GenericStrong,
	_TokenTypeName[1285:1302]:      GenericSubheading,
	_TokenTypeLowerName[1285:1302]: GenericSubheading,
	_TokenTypeName[1302:1318]:      GenericTraceback,
	_TokenTypeLowerName[1302:1318]: GenericTraceback,
	_TokenTypeName[1318:1334]:      GenericUnderline,
	_TokenTypeLowerName[1318:1334]: GenericUnderline,
	_TokenTypeName[1334:1338]:      Text,
	_TokenTypeLowerName[1334:1338]: Text,
	_TokenTypeName[1338:1352]:      TextWhitespace,
	_TokenTypeLowerName[1338:1352]: TextWhitespace,
	_TokenTypeName[1352:1362]:      TextSymbol,
	_TokenTypeLowerName[1352:1362]: TextSymbol,
	_TokenTypeName[1362:1377]:      TextPunctuation,
	_TokenTypeLowerName[1362:1377]: TextPunctuation,
}

var _TokenTypeNames = []string{
	_TokenTypeName[0:6],
	_TokenTypeName[6:10],
	_TokenTypeName[10:15],
	_TokenTypeName[15:20],
	_TokenTypeName[20:28],
	_TokenTypeName[28:36],
	_TokenTypeName[36:47],
	_TokenTypeName[47:56],
	_TokenTypeName[56:67],
	_TokenTypeName[67:76],
	_TokenTypeName[76:89],
	_TokenTypeName[89:105],
	_TokenTypeName[105:116],
	_TokenTypeName[116:120],
	_TokenTypeName[120:130],
	_TokenTypeName[130:140],
	_TokenTypeName[140:147],
	_TokenTypeName[147:154],
	_TokenTypeName[154:169],
	_TokenTypeName[169:187],
	_TokenTypeName[187:203],
	_TokenTypeName[203:216],
	_TokenTypeName[216:231],
	_TokenTypeName[231:242],
	_TokenTypeName[242:246],
	_TokenTypeName[246:259],
	_TokenTypeName[259:268],
	_TokenTypeName[268:280],
	_TokenTypeName[280:293],
	_TokenTypeName[293:303],
	_TokenTypeName[303:316],
	_TokenTypeName[316:327],
	_TokenTypeName[327:336],
	_TokenTypeName[336:349],
	_TokenTypeName[349:361],
	_TokenTypeName[361:370],
	_TokenTypeName[370:380],
	_TokenTypeName[380:392],
	_TokenTypeName[392:399],
	_TokenTypeName[399:410],
	_TokenTypeName[410:427],
	_TokenTypeName[427:439],
	_TokenTypeName[439:460],
	_TokenTypeName[460:477],
	_TokenTypeName[477:495],
	_TokenTypeName[495:515],
	_TokenTypeName[515:532],
	_TokenTypeName[532:544],
	_TokenTypeName[544:561],
	_TokenTypeName[561:568],
	_TokenTypeName[568:579],
	_TokenTypeName[579:591],
	_TokenTypeName[591:604],
	_TokenTypeName[604:622],
	_TokenTypeName[622:639],
	_TokenTypeName[639:660],
	_TokenTypeName[660:680],
	_TokenTypeName[680:697],
	_TokenTypeName[697:719],
	_TokenTypeName[719:735],
	_TokenTypeName[735:754],
	_TokenTypeName[754:773],
	_TokenTypeName[773:793],
	_TokenTypeName[793:814],
	_TokenTypeName[814:831],
	_TokenTypeName[831:849],
	_TokenTypeName[849:867],
	_TokenTypeName[867:886],
	_TokenTypeName[886:905],
	_TokenTypeName[905:918],
	_TokenTypeName[918:934],
	_TokenTypeName[934:952],
	_TokenTypeName[952:968],
	_TokenTypeName[968:988],
	_TokenTypeName[988:1012],
	_TokenTypeName[1012:1028],
	_TokenTypeName[1028:1045],
	_TokenTypeName[1045:1053],
	_TokenTypeName[1053:1065],
	_TokenTypeName[1065:1076],
	_TokenTypeName[1076:1083],
	_TokenTypeName[1083:1098],
	_TokenTypeName[1098:1114],
	_TokenTypeName[1114:1127],
	_TokenTypeName[1127:1141],
	_TokenTypeName[1141:1155],
	_TokenTypeName[1155:1173],
	_TokenTypeName[1173:1180],
	_TokenTypeName[1180:1194],
	_TokenTypeName[1194:1205],
	_TokenTypeName[1205:1217],
	_TokenTypeName[1217:1231],
	_TokenTypeName[1231:1246],
	_TokenTypeName[1246:1259],
	_TokenTypeName[1259:1272],
	_TokenTypeName[1272:1285],
	_TokenTypeName[1285:1302],
	_TokenTypeName[1302:1318],
	_TokenTypeName[1318:1334],
	_TokenTypeName[1334:1338],
	_TokenTypeName[1338:1352],
	_TokenTypeName[1352:1362],
	_TokenTypeName[1362:1377],
}

// TokenTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TokenTypeString(s string) (TokenType, error) {
	if val, ok := _TokenTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TokenTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TokenType values", s)
}

// TokenTypeValues returns all values of the enum
func TokenTypeValues() []TokenType {
	return _TokenTypeValues
}

// TokenTypeStrings returns a slice of all String values of the enum
func TokenTypeStrings() []string {
	strs := make([]string, len(_TokenTypeNames))
	copy(strs, _TokenTypeNames)
	return strs
}

// IsATokenType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TokenType) IsATokenType() bool {
	_, ok := _TokenTypeMap[i]
	return ok
}

// MarshalText implements the encoding.TextMarshaler interface for TokenType
func (i TokenType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TokenType
func (i *TokenType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TokenTypeString(string(text))
	return err
}
